language: php

php:
  - 7.3
  - 7.4

os: linux
dist: bionic

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text
